apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-backend
  template:
    metadata:
      labels:
        app: person-backend
    spec:
      containers:
      - name: backend
        image: person-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: person-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
