apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-frontend
  template:
    metadata:
      labels:
        app: person-frontend
    spec:
      containers:
      - name: frontend
        image: person-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: person-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
