apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cGVyc29udXNlcg==      # base64 for 'personuser'
  POSTGRES_PASSWORD: cGVyc29ucGFzcw==  # base64 for 'personpass'
